### ISSUE TITLE
Offset is out of bounds

### ISSUE THREAD

**Issue by ghost** [indutny/node.gzip#5]
Greetings,

I'm getting the following error:

throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Offset is out of bounds
    at Socket._writeImpl (net.js:159:14)
    at Socket._writeOut (net.js:450:25)
    at Socket.write (net.js:377:17)
    at /home/hynese/backopt/server7.js:30:7
    at ChildProcess.<anonymous> (/home/hynese/backopt/node.gunzip/lib/gunzip/index.js:41:7)
    at ChildProcess.emit (events.js:81:20)
    at ChildProcess.onexit (child_process.js:192:12)

I tried looking at the index.js code, line 41 - I think it's something to do with the buffer size. But I can't seem to figure it out.

Great project btw,

**Comment by ghost** [comment]
Hey, I'm still having this issue and was wondering if anyone could have a look at it? Many thanks,
